### ISSUE TITLE
Task :buildSrc:compileKotlin FAILED

### ISSUE THREAD

**Issue by freemmer** [developersancho/JetRorty.Android#16]
> Task :buildSrc:compileKotlin FAILED
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-compose.gradle.kts: (11, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-compose.gradle.kts: (11, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-compose.gradle.kts: (12, 5): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun CommonExtension<*, *, *, *>.addComposeConfig(): Unit defined in extensions in file CommonExtensions.kt
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (11, 1): Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (11, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
internal val ComPluginGroup.android: ComAndroidPluginGroup defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPlatformPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val OrgJetbrainsKotlinPluginGroup.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
internal val PluginDependenciesSpec.android: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._466e4a4700bc37c094a10aeb87c8c736 in file PluginSpecBuilders.kt
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (12, 5): Unresolved reference: compileSdk
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (14, 5): Unresolved reference: defaultConfig
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (15, 9): Unresolved reference: minSdk
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (16, 9): Unresolved reference: targetSdk
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (17, 9): Unresolved reference: testInstrumentationRunner
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (18, 9): Unresolved reference: consumerProguardFiles
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (21, 5): Unresolved reference: buildTypes
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (22, 9): Unresolved reference: release
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (23, 13): Unresolved reference: isMinifyEnabled
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (24, 13): Unresolved reference: proguardFiles
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (25, 17): Unresolved reference: getDefaultProguardFile
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (28, 13): Unresolved reference: buildConfigField
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (29, 13): Unresolved reference: buildConfigField
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (32, 9): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun CompileOptions.debug(vararg debugArgs: Pair<String, Any?>): CompileOptions defined in org.gradle.kotlin.dsl
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (33, 13): Unresolved reference: buildConfigField
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (34, 13): Unresolved reference: buildConfigField
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (38, 5): Unresolved reference: compileOptions
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (39, 9): Unresolved reference: sourceCompatibility
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (40, 9): Unresolved reference: targetCompatibility
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (43, 5): Unresolved reference: kotlinOptions
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (44, 9): Unresolved reference: jvmTarget
e: /Users/JetRorty.Android/buildSrc/src/main/java/commons/android-library.gradle.kts: (45, 9): Unresolved reference: freeCompilerArgs

**Comment by developersancho** [comment]
can you try with Android Studio Chipmunk @freemmer

**Comment by aaevseev** [comment]
I have same issue right now. Can't build project.

macOS Sonoma 14.0 and Android Studio Flamingo | 2022.2.1 Patch 2.
