### ISSUE TITLE
Previous screen is shown when press device back button from MainActivity

### ISSUE THREAD

**Issue by imranhsn** [developersancho/JetRorty.Android#17]
I found an issue with the screen navigation. When we open MainActivity from Splash and Welcome screen the previous activity should be finished. In the current behavior, it shows previous activity. Please check below screen transition,

case 1: 

SplashScreen -> WelcomeScreen -> MainScreen

When we press the back button WelcomeScreen it shows SplashScreen. The same things happen for MainScreen. It opens the WelcomeScreen.

case 2:

SplashScreen -> MainScreen

Here it opens SplashScreen. When clicking the back button the app should close.

**Comment by developersancho** [comment]
thanks your fix @imranhsn
